### ISSUE TITLE
Don't draw rectangle when selectorStyle = classic

### ISSUE THREAD

**Issue by tsuharesu** [tomeeeS/ScrollPicker#1]
I see that the view is always drawing a rectangle. Is there a way that it is not needed when using classic?

I'm using this inside a parent that have `android:clipChildren="false"` so the children are allowed to draw outside their bounds (I need this for another custom view with shadow). However, the picker is showing the rectangle. If I remove it, then the picker does not draw the rectangle.

**Comment by tomeeeS** [comment]
Ah yes, it was just easier to code it that way and I thought there won't be any problems with that x)
I'll fix it very soon, thanks for the feedback!

**Comment by tomeeeS** [comment]
fixed in version 1.7.3
